version: "3"

networks:
  my-net:
    external: true

services:
  game-dejavu:
    image: game-dejavu
    container_name: game-dejavu-container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    networks:
      - my-net